### ISSUE TITLE
[MaskRCNN/Tensorflow2] MaskRCNN distributed training crashes with Tensorflow 2.6

### ISSUE THREAD

**Issue by rondogency** [NVIDIA/DeepLearningExamples#1006]
Related to **Model/Framework(s)** 
MaskRCNN/Tensorflow2

**Describe the bug**
MaskRCNN distributed training crashes with Tensorflow 2.6, which it works fine in Tensorflow 2.4

There are 2 crashes after upgrading binary to public tensorflow-gpu==2.6

1. AttributeError: module 'tensorflow._api.v2.data.experimental' has no attribute 'MapVectorizationOptions' crash, which can be fixed by commenting out lines regarding tf.data.experimental.MapVectorizationOptions(), and no performance/convergence regression changed from that

2. TypeError("Failed to convert object of type %s to Tensor. ") after training when trying to save the tensor, see below traceback for error message

**To Reproduce**
Following https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow2/Segmentation/MaskRCNN do build the NGC container

Then login the container and run 'pip install tensorflow-gpu==2.6' to install latest public TF binary

After that, launch training by 'python main.py train --data_dir /tmp/maskrcnn/train --backbone_checkpoint /weights/rn50_tf_amp_ckpt_v20.06.0/nvidia_rn50_tf_amp --epochs 1 --steps_per_epoch 200 --log_every 10 --train_batch_size 4'

**Expected behavior**
Training runs and terminates gracefully like TF 2.4

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): nvcr.io/nvidia/tensorflow:21.02-tf2-py3
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): 8x Tesla V100-SXM2-16GB
* CUDA driver version (e.g. 418.67): 450.142.00

Traceback:
Epoch 00001: saving model to /results/nvidia_mrcnn_tf2.ckpt
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    main()
  File "main.py", line 61, in main
    run_training(dataset, params)
  File "/workspace/mrcnn_tf2/mrcnn_tf2/runtime/run.py", line 54, in run_training
    mask_rcnn_model.fit(
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1230, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.8/dist-packages/keras/callbacks.py", line 413, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.8/dist-packages/keras/callbacks.py", line 1368, in on_epoch_end
    self._save_model(epoch=epoch, batch=None, logs=logs)
  File "/usr/local/lib/python3.8/dist-packages/keras/callbacks.py", line 1434, in _save_model
    self.model.save(filepath, overwrite=True, options=self._options)
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 2145, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 149, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/save.py", line 90, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1228, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1399, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1335, in _build_meta_graph_impl
    signatures = signature_serialization.find_function_to_export(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/signature_serialization.py", line 99, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 163, in list_functions
    obj_functions = obj._list_functions_for_serialization(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 2812, in _list_functions_for_serialization
    functions = super(
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 3085, in _list_functions_for_serialization
    return (self._trackable_saved_model_saver
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/base_serialization.py", line 93, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/layer_serialization.py", line 73, in functions_to_serialize
    return (self._get_serialized_attributes(
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/layer_serialization.py", line 89, in _get_serialized_attributes
    object_dict, function_dict = self._get_serialized_attributes_internal(
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/model_serialization.py", line 51, in _get_serialized_attributes_internal
    default_signature = save_impl.default_save_signature(self.obj)
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/save_impl.py", line 208, in default_save_signature
    fn = saving_utils.trace_model_call(layer)
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saving_utils.py", line 135, in trace_model_call
    return _wrapped_model.get_concrete_function(*model_args, **model_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 1233, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 1213, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 759, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3298, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /usr/local/lib/python3.8/dist-packages/keras/saving/saving_utils.py:125 _wrapped_model  *
        outputs = model(*args, **kwargs)
    /workspace/mrcnn_tf2/mrcnn_tf2/model/mask_rcnn.py:103 call  *
        rpn_box_scores, rpn_box_rois = roi_ops.multilevel_propose_rois(
    /workspace/mrcnn_tf2/mrcnn_tf2/ops/roi_ops.py:182 multilevel_propose_rois  *
        this_level_scores = tf.reshape(scores_outputs[level], [batch_size, num_boxes])
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/array_ops.py:196 reshape
        result = gen_array_ops.reshape(tensor, shape, name)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_array_ops.py:8403 reshape
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/op_def_library.py:525 _apply_op_helper
        raise err
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/op_def_library.py:511 _apply_op_helper
        values = ops.convert_to_tensor(
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py:346 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py:271 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py:288 _constant_impl
        tensor_util.make_tensor_proto(
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/tensor_util.py:551 make_tensor_proto
        raise TypeError("Failed to convert object of type %s to Tensor. "

    TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, 209664]. Consider casting elements to a supported type.Epoch 00001: saving model to /results/nvidia_mrcnn_tf2.ckpt
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    main()
  File "main.py", line 61, in main
    run_training(dataset, params)
  File "/workspace/mrcnn_tf2/mrcnn_tf2/runtime/run.py", line 54, in run_training
    mask_rcnn_model.fit(
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1230, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.8/dist-packages/keras/callbacks.py", line 413, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.8/dist-packages/keras/callbacks.py", line 1368, in on_epoch_end
    self._save_model(epoch=epoch, batch=None, logs=logs)
  File "/usr/local/lib/python3.8/dist-packages/keras/callbacks.py", line 1434, in _save_model
    self.model.save(filepath, overwrite=True, options=self._options)
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 2145, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/save.py", line 149, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/save.py", line 90, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1228, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1399, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1335, in _build_meta_graph_impl
    signatures = signature_serialization.find_function_to_export(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/signature_serialization.py", line 99, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 163, in list_functions
    obj_functions = obj._list_functions_for_serialization(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 2812, in _list_functions_for_serialization
    functions = super(
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 3085, in _list_functions_for_serialization
    return (self._trackable_saved_model_saver
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/base_serialization.py", line 93, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/layer_serialization.py", line 73, in functions_to_serialize
    return (self._get_serialized_attributes(
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/layer_serialization.py", line 89, in _get_serialized_attributes
    object_dict, function_dict = self._get_serialized_attributes_internal(
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/model_serialization.py", line 51, in _get_serialized_attributes_internal
    default_signature = save_impl.default_save_signature(self.obj)
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saved_model/save_impl.py", line 208, in default_save_signature
    fn = saving_utils.trace_model_call(layer)
  File "/usr/local/lib/python3.8/dist-packages/keras/saving/saving_utils.py", line 135, in trace_model_call
    return _wrapped_model.get_concrete_function(*model_args, **model_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 1233, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 1213, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 759, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3298, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /usr/local/lib/python3.8/dist-packages/keras/saving/saving_utils.py:125 _wrapped_model  *
        outputs = model(*args, **kwargs)
    /workspace/mrcnn_tf2/mrcnn_tf2/model/mask_rcnn.py:103 call  *
        rpn_box_scores, rpn_box_rois = roi_ops.multilevel_propose_rois(
    /workspace/mrcnn_tf2/mrcnn_tf2/ops/roi_ops.py:182 multilevel_propose_rois  *
        this_level_scores = tf.reshape(scores_outputs[level], [batch_size, num_boxes])
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py:206 wrapper  **
        return target(*args, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/array_ops.py:196 reshape
        result = gen_array_ops.reshape(tensor, shape, name)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_array_ops.py:8403 reshape
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/op_def_library.py:525 _apply_op_helper
        raise err
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/op_def_library.py:511 _apply_op_helper
        values = ops.convert_to_tensor(
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py:346 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py:271 constant
        return _constant_impl(value, dtype, shape, name, verify_shape=False,
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/constant_op.py:288 _constant_impl
        tensor_util.make_tensor_proto(
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/tensor_util.py:551 make_tensor_proto
        raise TypeError("Failed to convert object of type %s to Tensor. "

    TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, 209664]. Consider casting elements to a supported type.
