### ISSUE TITLE
fastertransformer compile error with pytorch

### ISSUE THREAD

**Issue by mingxin-zhou** [NVIDIA/DeepLearningExamples#661]
**enviroment:**
GPU: Titan xp
gcc: 5.4.0 (GCC)
cmake: 3.15.2
CUDA: 10.1
cudnn: 7
pytorch: 1.4.0

**cmake -DSM=61 -DCMAKE_BUILD_TYPE=Release -DBUILD_THE=ON -DCXX_STD=11 ..**
output:
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is NVIDIA 10.1.105
-- Check for working CXX compiler: /usr/local/bin/c++
-- Check for working CXX compiler: /usr/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "10.1", minimum required is "10.0") 
-- Found CUDA: /usr/local/cuda (found version "10.1") 
-- Assign GPU architecture (sm=61)
-- Found CUDA: /usr/local/cuda (found version "10.1") 
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.1
-- Found CUDNN: /usr/local/cuda/lib64/libcudnn.so  
-- Found cuDNN: v7.5.0  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
CMake Warning at /home/zhoumingxin/anaconda3/envs/fast_transfomer/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/utils.cmake:196 (message):
  In the future we will require one to explicitly pass TORCH_CUDA_ARCH_LIST
  to cmake instead of implicitly setting it as an env variable.  This will
  become a FATAL_ERROR in future version of pytorch.
Call Stack (most recent call first):
  /home/zhoumingxin/anaconda3/envs/fast_transfomer/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:395 (torch_cuda_get_nvcc_gencode_flag)
  /home/zhoumingxin/anaconda3/envs/fast_transfomer/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)  /home/zhoumingxin/anaconda3/envs/fast_transfomer/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:130 (find_package)

-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Found torch: /home/zhoumingxin/anaconda3/envs/fast_transfomer/lib/python3.7/site-packages/torch/lib/libtorch.so  
-c:3: DeprecationWarning: SO is deprecated, use EXT_SUFFIX
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zhoumingxin/code/DeepLearningExamples/FasterTransformer/v2.1/build

**make**
output:
...
[ 60%] Building CXX object fastertransformer/th_op/CMakeFiles/th_fastertransformer.dir/ft_ext.cc.o
[ 64%] Building CXX object fastertransformer/th_op/CMakeFiles/th_fastertransformer.dir/encoder_ext.cc.o
[ 67%] Building CXX object fastertransformer/th_op/CMakeFiles/th_fastertransformer.dir/decoder_ext.cc.o
[ 71%] Building CXX object fastertransformer/th_op/CMakeFiles/th_fastertransformer.dir/decoding_ext.cc.o
[ 75%] Building CUDA object fastertransformer/th_op/CMakeFiles/th_fastertransformer.dir/utils.cu.o
[ 78%] Linking CXX shared library ../../th_fastertransformer.cpython-37m-x86_64-linux-gnu.so
[ 78%] Built target th_fastertransformer
Scanning dependencies of target decoding_sampling_sample
[ 82%] Building CXX object sample/cpp/CMakeFiles/decoding_sampling_sample.dir/decoding_sampling_sample.cc.o
[ 85%] Linking CXX executable ../../bin/decoding_sampling_sample
../../lib/libdecoder.a(open_decoder.cu.o): In function `__sti____cudaRegisterAll()':
tmpxft_00006dbd_00000000-5_open_decoder.cudafe1.cpp:(.text.startup+0x1d): undefined reference to `__cudaRegisterLinkedBinary_47_tmpxft_00006dbd_00000000_6_open_decoder_cpp1_ii_35623ad2'
../../lib/libdecoding.a(decoding_kernels.cu.o): In function `__sti____cudaRegisterAll()':
tmpxft_00006e36_00000000-5_decoding_kernels.cudafe1.cpp:(.text.startup+0x1d): undefined reference to `__cudaRegisterLinkedBinary_51_tmpxft_00006e36_00000000_6_decoding_kernels_cpp1_ii_74f691b0'
../../lib/libtopk.a(topk_kernels.cu.o): In function `__sti____cudaRegisterAll()':
tmpxft_00006de5_00000000-5_topk_kernels.cudafe1.cpp:(.text.startup+0x1d): undefined reference to `__cudaRegisterLinkedBinary_47_tmpxft_00006de5_00000000_6_topk_kernels_cpp1_ii_8929a6bd'
../../lib/libcuda_kernels.a(cuda_kernels.cu.o): In function `__sti____cudaRegisterAll()':
tmpxft_00006d41_00000000-5_cuda_kernels.cudafe1.cpp:(.text.startup+0x1d): undefined reference to `__cudaRegisterLinkedBinary_47_tmpxft_00006d41_00000000_6_cuda_kernels_cpp1_ii_3f73e706'
collect2: error: ld returned 1 exit status
sample/cpp/CMakeFiles/decoding_sampling_sample.dir/build.make:88: recipe for target 'bin/decoding_sampling_sample' failed
make[2]: *** [bin/decoding_sampling_sample] Error 1
CMakeFiles/Makefile2:509: recipe for target 'sample/cpp/CMakeFiles/decoding_sampling_sample.dir/all' failed
make[1]: *** [sample/cpp/CMakeFiles/decoding_sampling_sample.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by byshiue** [comment]
Thanks for your feedback.
We have reproduced your problem, and find that it works on cmake 3.14. 
You can try to compile FasterTransformer under cmake 3.14 first.

**Comment by mingxin-zhou** [comment]
Thanks, I'll try cmake 3.14

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this bug if you still have any problem.
